import {
  LayoutDashboard,
  Users,
  Stethoscope,
  Calendar,
  FileText,
  FlaskConical,
  ClipboardList,
  Pill,
  Receipt,
  CreditCard,
  Bell,
  CalendarClock,
  UserCircle,
  Bot,
} from 'lucide-react'
import { ROLES } from './constants'

export const NAV_ITEMS = {
  [ROLES.ADMIN]: [
    { label: 'Dashboard', path: '/admin/dashboard', icon: LayoutDashboard },
    { label: 'Doctors', path: '/admin/doctors', icon: Stethoscope },
    { label: 'Patients', path: '/admin/patients', icon: Users },
    { label: 'Appointments', path: '/admin/appointments', icon: Calendar },
    { label: 'Prescriptions', path: '/admin/prescriptions', icon: FileText },
    { label: 'Lab Reports', path: '/admin/lab-reports', icon: FlaskConical },
    { label: 'Medical History', path: '/admin/medical-history', icon: ClipboardList },
    { label: 'Medicines', path: '/admin/medicines', icon: Pill },
    { label: 'Pharmacy Sales', path: '/admin/pharmacy-sales', icon: Pill },
    { label: 'Invoices', path: '/admin/invoices', icon: Receipt },
    { label: 'Payments', path: '/admin/payments', icon: CreditCard },
    { label: 'Notifications', path: '/admin/notifications', icon: Bell },
    {
  label: 'AI Assistant',
  path: '/admin/ai-assistant',
  icon: Bot,
},
  ],
  [ROLES.DOCTOR]: [
    { label: 'Dashboard', path: '/doctor/dashboard', icon: LayoutDashboard },
    { label: 'My Schedule', path: '/doctor/schedule', icon: CalendarClock },
    { label: 'Appointments', path: '/doctor/appointments', icon: Calendar },
    { label: 'Patients', path: '/doctor/patients', icon: Users },
    { label: 'Prescriptions', path: '/doctor/prescriptions', icon: FileText },
    { label: 'Lab Reports', path: '/doctor/lab-reports', icon: FlaskConical },
    { label: 'Medical History', path: '/doctor/medical-history', icon: ClipboardList },
    { label: 'Profile', path: '/doctor/profile', icon: UserCircle },
    { label: 'Notifications', path: '/doctor/notifications', icon: Bell },
    {
  label: 'AI Assistant',
  path: '/doctor/ai-assistant',
  icon: Bot,
},
  ],
  [ROLES.PATIENT]: [
    { label: 'Dashboard', path: '/patient/dashboard', icon: LayoutDashboard },
    { label: 'My Profile', path: '/patient/profile', icon: UserCircle },
    { label: 'Find Doctors', path: '/patient/doctors', icon: Stethoscope },
    { label: 'Book Appointment', path: '/patient/book-appointment', icon: Calendar },
    { label: 'Appointments', path: '/patient/appointments', icon: CalendarClock },
    { label: 'Prescriptions', path: '/patient/prescriptions', icon: FileText },
    { label: 'Lab Reports', path: '/patient/lab-reports', icon: FlaskConical },
    { label: 'Medical History', path: '/patient/medical-history', icon: ClipboardList },
    { label: 'Pharmacy', path: '/patient/pharmacy', icon: Pill },
    { label: 'Payments', path: '/patient/payments', icon: CreditCard },
    { label: 'Invoices', path: '/patient/invoices', icon: Receipt },
    { label: 'Notifications', path: '/patient/notifications', icon: Bell },
    {
  label: 'AI Assistant',
  path: '/patient/ai-assistant',
  icon: Bot,
},
  ],
}
